/* eslint-disable */
// AUTO-GENERATED by scripts/generate-environment.mjs — do not edit manually.
// Configure via client/.env (copy from .env.example) or Vercel environment variables.

export interface EnvironmentConfig {
  production: boolean;
  graphqlHttpUri: string;
  graphqlWsUri: string;
  auth0: {
    domain: string;
    clientId: string;
    audience: string;
    redirectUri: string;
  };
  devAuthBypass: boolean;
}

function toEnvironment(cfg: {
  graphqlHttpUri: string;
  graphqlWsUri: string;
  auth0Domain: string;
  auth0ClientId: string;
  auth0Audience: string;
  devAuthBypass: boolean;
}, production: boolean): EnvironmentConfig {
  const redirectUri =
    typeof window !== 'undefined' ? window.location.origin : production ? '' : 'http://localhost:4200';
  return {
    production,
    graphqlHttpUri: cfg.graphqlHttpUri,
    graphqlWsUri: cfg.graphqlWsUri,
    auth0: {
      domain: cfg.auth0Domain,
      clientId: cfg.auth0ClientId,
      audience: cfg.auth0Audience,
      redirectUri,
    },
    devAuthBypass: cfg.devAuthBypass,
  };
}

const devCfg = {
  "graphqlHttpUri": "http://localhost:4000/graphql",
  "graphqlWsUri": "ws://localhost:4000/graphql",
  "auth0Domain": "dev-7a62dtp61wilsbm7.us.auth0.com",
  "auth0ClientId": "P1FAQhNgqSVHPoI95irT3K9TxkuOiach",
  "auth0Audience": "https://task-dashboard-api",
  "devAuthBypass": false
};
const prodCfg = {
  "graphqlHttpUri": "http://localhost:4000/graphql",
  "graphqlWsUri": "ws://localhost:4000/graphql",
  "auth0Domain": "dev-7a62dtp61wilsbm7.us.auth0.com",
  "auth0ClientId": "P1FAQhNgqSVHPoI95irT3K9TxkuOiach",
  "auth0Audience": "https://task-dashboard-api",
  "devAuthBypass": true
};

export const developmentEnvironment = toEnvironment(devCfg, true);
export const productionEnvironment = toEnvironment(prodCfg, false);
